development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: inspire_development
  pool: 5
  username: wataru
  password:
  host: localhost
  
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: inspire_test
  pool: 5
  username: wataru
  password:
  host: localhost